const data = [
  {
    img: "https://raw.githubusercontent.com/maligaurav947/Portfolio/a2b34534720ed96ebfd94a38da7495fc4a1b5663/src/reso/Reactecommercestoere.png",
    title: "React Ecommerce Store",
    info: "A React Ecommerce Store That Containe Store Management",
    link: "https://maligaurav947.github.io/react-ecommerce-store/",
    github: "https://github.com/maligaurav947/react-ecommerce-store",
    s1: "react",
    s2: "css3-alt",
    val: "imghvr-push-down",
    aos: "fade-right",
  },
  {
    img: "https://raw.githubusercontent.com/maligaurav947/Portfolio/672a8cebf04152bf4e884fe737bfbfed2a895938/src/reso/Weather-react-app.png",
    title: "React Weather App",
    info: "A React Weather App That Containe Weather Data From Api",
    link: "https://maligaurav947.github.io/react-weather-app/",
    github: "https://github.com/maligaurav947/react-weather-app/tree/master",
    s1: "react",
    s2: "css3-alt",
    val: "imghvr-push-up",
    aos: "fade-center",
  },
  {
    img: "https://raw.githubusercontent.com/maligaurav947/Portfolio/567840b07268318cba69fd5c50315781e7326d69/src/reso/Screenshot%202023-01-03%20002533.png",
    title: "Quiz Game React",
    info: "A React quiz application related to trivia knowledge which generates random questions",
    link: "https://maligaurav947.github.io/quiz-react/",
    github: "https://github.com/maligaurav947/quiz-react/tree/master",
    s1: "react",
    s2: "css3-alt",
    val: "imghvr-push-right",
    aos: "fade-left",
  },
  {
    img: "https://raw.githubusercontent.com/maligaurav947/Portfolio/744ae5f79bbe0623dc67fbb63a2afb5db32eed2d/src/res/Student.png",
    title: "Student Details System",
    info: "BTECH Finally Year Project Content Firebase DATABASE React.js",
    link: "https://maligaurav947.github.io/student-details/",
    github: "https://github.com/maligaurav947/student-details",
    s1: "react",
    s2: "css3-alt",
    s3: "database",
    val: "imghvr-push-up",
    aos: "fade-right",
  },
  {
    img: "https://github.com/maligaurav947/Portfolio/blob/master/src/reso/screencapture-maligaurav947-github-io-news-2022-11-11-09_32_37.png?raw=true",
    title: "News",
    info: "Collection of New / Breaking News Collected By News Data API",
    link: "https://maligaurav947.github.io/news/",
    github: "https://github.com/maligaurav947/news",
    s1: "react",
    s2: "css3-alt",
    s3: "retweet",
    val: "imghvr-zoom-out-up",
    aos: "fade-center",
  },
  {
    img: "https://user-images.githubusercontent.com/86152880/197372331-04bcc17f-1e95-4e80-b078-460ba3bf4d46.png",
    title: "Libary List ",
    info: "The Project Content All Type Of Library.The Basic Goal of This Project The Collect All Type Of Library And Show Them One Place",
    link: "https://maligaurav947.github.io/library-list-react/",
    github: "https://github.com/maligaurav947/library-list-react",
    s1: "react",
    s2: "css3-alt",
    s3: "",
    val: "imghvr-push-up",
    aos: "fade-left",
  },
  {
    img: "https://github.com/maligaurav947/Portfolio/blob/master/src/reso/toy-shop.png?raw=true",
    title: "Toy Shop",
    info: "Toy Shop Content Small Amount Of Account Mangement , Card System, Login Section",
    link: "https://maligaurav947.github.io/toy-shop/",
    github: "https://github.com/maligaurav947/toy-shop",
    s1: "react",
    s2: "css3-alt",
    s3: "js",
    val: "imghvr-shutter-out-vert",
    aos: "fade-right",
  },
  {
    img: "https://github.com/maligaurav947/Portfolio/blob/master/src/reso/bank-developer.png?raw=true",
    title: "Bank For Developer",
    info: "Bank For Developer Content Small Amount Of Account Mangement, Login Section. Every Special User Have There Own Dashboard",
    link: "https://maligaurav947.github.io/Bank-developer/",
    github: "https://github.com/maligaurav947/Bank-developer",
    s1: "html5",
    s2: "css3-alt",
    s3: "js",
    val: "imghvr-slide-down",
    aos: "fade-center",
  },
  {
    img: "https://github.com/maligaurav947/Portfolio/blob/master/src/reso/show-case.png?raw=true",
    title: "Show Case",
    info: "This Project Content My Small Project And Some Try Out Library / framework",
    link: "https://maligaurav947.github.io/ShowCase/",
    github: "https://github.com/maligaurav947/ShowCase",
    s1: "html5",
    s2: "css3-alt",
    s3: "",
    val: "imghvr-hinge-up",
    aos: "fade-lef",
  },
];

export default data;
